name: german-sentiment-bert
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/german-sentiment-bert
  original_url: https://huggingface.co/spaces/Chris4K/german-sentiment-bert

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 13:26:18
